name: edenroot
description: Eden's cognitive architecture and emotional processing system
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  uuid: ^4.0.0
  http: ^1.1.0
  intl: ^0.20.2  # Updated from 0.18.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0  # Updated from 3.0.0